// <auto-generated />
namespace lifu.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Addinit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addinit));
        
        string IMigrationMetadata.Id
        {
            get { return "201602041109180_Addinit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
